[package]
name = "file-size"
edition = "2021"
publish = false

[dependencies]
bevy.workspace = true

[profile.release]
# Link time optimizations.
lto = "thin"
# Strip debuginfo and symbols from binary.
# strip = true
